DROP TABLE IF EXISTS `rs_merchant_info`;

CREATE TABLE `rs_merchant_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mchId` varchar(32) DEFAULT NULL,
  `submchid` varchar(32) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `province` varchar(16) DEFAULT NULL,
  `provincename` varchar(64) DEFAULT NULL,
  `city` varchar(16) DEFAULT NULL,
  `cityname` varchar(64) DEFAULT NULL,
  `area` varchar(16) DEFAULT NULL,
  `areaname` varchar(64) DEFAULT NULL,
  `address` varchar(128) DEFAULT NULL,
  `legelname` varchar(32) DEFAULT NULL,
  `legelcertno` varchar(32) DEFAULT NULL,
  `email` varchar(32) DEFAULT NULL,
  `phone` varchar(16) DEFAULT NULL,
  `bankno` varchar(32) DEFAULT NULL,
  `bankname` varchar(64) DEFAULT NULL,
  `branchno` varchar(32) DEFAULT NULL,
  `branchname` varchar(64) DEFAULT NULL,
  `cardno` varchar(32) DEFAULT NULL,
  `ecardno` varchar(32) DEFAULT NULL,
  `payname` varchar(32) DEFAULT NULL,
  `payphone` varchar(16) DEFAULT NULL,
  `cardprovince` varchar(16) DEFAULT NULL,
  `cardprovincename` varchar(64) DEFAULT NULL,
  `cardcity` varchar(16) DEFAULT NULL,
  `cardcityname` varchar(64) DEFAULT NULL,
  `cardarea` varchar(16) DEFAULT NULL,
  `cardareaname` varchar(64) DEFAULT NULL,
  `type` varchar(8) DEFAULT NULL,
  `certtype` varchar(8) DEFAULT NULL,
  `certno` varchar(32) DEFAULT NULL,
  `buslicpic` varchar(128) DEFAULT NULL,
  `legfrontpic` varchar(128) DEFAULT NULL,
  `handpic` varchar(128) DEFAULT NULL,
  `doorpic` varchar(128) DEFAULT '',
  `legbackpic` varchar(128) DEFAULT NULL,
  `accopenpic` varchar(128) DEFAULT NULL,
  `cashierpic` varchar(128) DEFAULT NULL,
  `rate` varchar(10) DEFAULT NULL,
  `fee` varchar(10) DEFAULT NULL,
  `remark` varchar(256) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `version` int(11) DEFAULT '0',
  `modify_time` datetime DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

